### ISSUE TITLE
Design web page typography

### ISSUE THREAD

**Issue by wendybaum** [wendybaum/Bookly#27]
## User Story

As a user web pages should be able to be read without effort and eye strain, in addition to being aesthetically pleasing.

## Acceptance Criteria

- [ ] Text input font size should be of at least 16px
- [ ] Body font size should be around 16px
- [ ] Second text size should be 13px or 14px
- [x] Use Serif and sans fonts
- [x] Use web safe fonts

**Comment by rfinkley** [comment]
Let me know what you think of this type pairing.

The display type is a Cormorant Garamond variety, Serif type. This could be used for headings.

The subtitle is Roboto, sans-serif. I was thinking this could be used for the text input, it’s clean and looks nice on a solid background.

The paragraph type is Hind Vadodara, sans-serif. I was thinking this could be used for the body font.

They are each web safe and available from Google Fonts. 

![ADF09340-C73A-4F65-86E4-D53D356E8093](https://user-images.githubusercontent.com/46961208/73602123-68fd3380-453c-11ea-9fff-e5ca05e982dc.jpeg)
